Commit changes made by code formatters

diff --git a/terraform/environments/nomis/ssm-documents/templates/tempfile-aws-apply-ansible-playbook.yml b/terraform/environments/nomis/ssm-documents/templates/tempfile-aws-apply-ansible-playbook.yml
--- a/terraform/environments/nomis/ssm-documents/templates/tempfile-aws-apply-ansible-playbook.yml
+++ b/terraform/environments/nomis/ssm-documents/templates/tempfile-aws-apply-ansible-playbook.yml
@@ -1,5 +1,5 @@
 ---
-schemaVersion: '2.2'
+schemaVersion: "2.2"
 description: Use this document to run Ansible Playbooks on Systems Manager managed
   instances. For more information, see https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-state-manager-ansible.html.
 parameters:
@@ -7,8 +7,8 @@ parameters:
     description: "(Optional) Specify the source type."
     type: String
     allowedValues:
-    - GitHub
-    - S3
+      - GitHub
+      - S3
   SourceInfo:
     description: '(Optional) Specify the information required to access the resource
       from the specified source type. If source type is GitHub, then you can specify
@@ -27,9 +27,9 @@ parameters:
       verify that Ansible and its dependencies are installed on the target instances.
       If they aren’t, the SSM document fails to run."
     allowedValues:
-    - 'True'
-    - 'False'
-    default: 'True'
+      - "True"
+      - "False"
+    default: "True"
   PlaybookFile:
     type: String
     description: "(Optional) The Playbook file to run (including relative path). If
@@ -52,93 +52,93 @@ parameters:
       Modules that don’t support check mode take no action and don’t report changes
       that would be made."
     allowedValues:
-    - 'True'
-    - 'False'
-    default: 'False'
+      - "True"
+      - "False"
+    default: "False"
   Verbose:
     type: String
     description: "(Optional) Set the verbosity level for logging Playbook executions.
       Specify -v for low verbosity, -vv or –vvv for medium verbosity, and -vvvv for
       debug level."
     allowedValues:
-    - "-v"
-    - "-vv"
-    - "-vvv"
-    - "-vvvv"
+      - "-v"
+      - "-vv"
+      - "-vvv"
+      - "-vvvv"
     default: "-v"
   TimeoutSeconds:
     type: String
     description: "(Optional) The time in seconds for a command to be completed before
       it is considered to have failed."
-    default: '3600'
+    default: "3600"
 mainSteps:
-- action: aws:downloadContent
-  name: downloadContent
-  inputs:
-    SourceType: "{{ SourceType }}"
-    SourceInfo: "{{ SourceInfo }}"
-- action: aws:runShellScript
-  name: runShellScript
-  inputs:
-    timeoutSeconds: "{{ TimeoutSeconds }}"
-    runCommand:
-    - "#!/bin/bash"
-    - if  [[ "{{InstallDependencies}}" == True ]] ; then
-    - '   echo "Installing and or updating required tools: Ansible, wget unzip ...."
-      >&2'
-    - '   if [ -f  "/etc/system-release" ] ; then'
-    - "     if cat /etc/system-release|grep -i 'Amazon Linux release 2' ; then "
-    - "       sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
-    - "       sudo yum install -y ansible"
-    - "       sudo yum -y install unzip"
-    - "     elif cat /etc/system-release|grep -i 'Amazon Linux AMI' ; then "
-    - "       sudo pip install ansible --upgrade"
-    - "       sudo yum -y install unzip"
-    - "     elif cat /etc/system-release|grep -i 'Red Hat Enterprise Linux' ; then "
-    - "       sudo yum -y install python3-pip"
-    - "       sudo pip3 install ansible"
-    - "       sudo yum -y install unzip"
-    - "     else"
-    - '       echo "There was a problem installing or updating the required tools
-      for the document. You can review the log files to help you correct the problem."
-      >&2'
-    - "       exit 1"
-    - "     fi"
-    - "   elif cat /etc/issue|grep -i Ubuntu ; then "
-    - "     UBUNTU_VERSION=$(cat /etc/issue | grep -i ubuntu | awk '{print $2}' |
-      \ awk -F'.' '{print $1}')"
-    - "     sudo apt-get update"
-    - "     if [ $(($UBUNTU_VERSION > 18)) == 1 ]; then"
-    - "       sudo DEBIAN_FRONTEND=noninteractive apt-get install python3-pip -y"
-    - "       sudo pip3 install ansible --upgrade"
-    - "     else"
-    - "       sudo DEBIAN_FRONTEND=noninteractive apt-get install python-pip -y"
-    - "       sudo pip install ansible --upgrade"
-    - "     fi"
-    - "     sudo DEBIAN_FRONTEND=noninteractive apt-get install unzip -y"
-    - "   else"
-    - '     echo "There was a problem installing or updating the required tools for
-      the document. You can review the log files to help you correct the problem."
-      >&2'
-    - "     exit 1"
-    - "   fi"
-    - fi
-    - echo "Running Ansible in `pwd`"
-    - "#this section locates files and unzips them"
-    - for zip in $(find -iname '*.zip'); do
-    - "  unzip -o $zip"
-    - done
-    - PlaybookFile="{{PlaybookFile}}"
-    - if [ ! -f  "${PlaybookFile}" ] ; then
-    - '   echo "The specified Playbook file doesn''t exist in the downloaded bundle.
-      Please review the relative path and file name." >&2'
-    - "   exit 2"
-    - fi
-    - if  [[ "{{Check}}" == True ]] ; then
-    - '   ansible-playbook -i "localhost," --check -c local -e "{{ExtraVariables}}"
-      "{{Verbose}}" "${PlaybookFile}"'
-    - else
-    - '   ansible-playbook -i "localhost," -c local -e "{{ExtraVariables}}" "{{Verbose}}"
-      "${PlaybookFile}"'
-    - fi
-# 
+  - action: aws:downloadContent
+    name: downloadContent
+    inputs:
+      SourceType: "{{ SourceType }}"
+      SourceInfo: "{{ SourceInfo }}"
+  - action: aws:runShellScript
+    name: runShellScript
+    inputs:
+      timeoutSeconds: "{{ TimeoutSeconds }}"
+      runCommand:
+        - "#!/bin/bash"
+        - if  [[ "{{InstallDependencies}}" == True ]] ; then
+        - '   echo "Installing and or updating required tools: Ansible, wget unzip ...."
+          >&2'
+        - '   if [ -f  "/etc/system-release" ] ; then'
+        - "     if cat /etc/system-release|grep -i 'Amazon Linux release 2' ; then "
+        - "       sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
+        - "       sudo yum install -y ansible"
+        - "       sudo yum -y install unzip"
+        - "     elif cat /etc/system-release|grep -i 'Amazon Linux AMI' ; then "
+        - "       sudo pip install ansible --upgrade"
+        - "       sudo yum -y install unzip"
+        - "     elif cat /etc/system-release|grep -i 'Red Hat Enterprise Linux' ; then "
+        - "       sudo yum -y install python3-pip"
+        - "       sudo pip3 install ansible"
+        - "       sudo yum -y install unzip"
+        - "     else"
+        - '       echo "There was a problem installing or updating the required tools
+          for the document. You can review the log files to help you correct the problem."
+          >&2'
+        - "       exit 1"
+        - "     fi"
+        - "   elif cat /etc/issue|grep -i Ubuntu ; then "
+        - "     UBUNTU_VERSION=$(cat /etc/issue | grep -i ubuntu | awk '{print $2}' |
+          \ awk -F'.' '{print $1}')"
+        - "     sudo apt-get update"
+        - "     if [ $(($UBUNTU_VERSION > 18)) == 1 ]; then"
+        - "       sudo DEBIAN_FRONTEND=noninteractive apt-get install python3-pip -y"
+        - "       sudo pip3 install ansible --upgrade"
+        - "     else"
+        - "       sudo DEBIAN_FRONTEND=noninteractive apt-get install python-pip -y"
+        - "       sudo pip install ansible --upgrade"
+        - "     fi"
+        - "     sudo DEBIAN_FRONTEND=noninteractive apt-get install unzip -y"
+        - "   else"
+        - '     echo "There was a problem installing or updating the required tools for
+          the document. You can review the log files to help you correct the problem."
+          >&2'
+        - "     exit 1"
+        - "   fi"
+        - fi
+        - echo "Running Ansible in `pwd`"
+        - "#this section locates files and unzips them"
+        - for zip in $(find -iname '*.zip'); do
+        - "  unzip -o $zip"
+        - done
+        - PlaybookFile="{{PlaybookFile}}"
+        - if [ ! -f  "${PlaybookFile}" ] ; then
+        - '   echo "The specified Playbook file doesn''t exist in the downloaded bundle.
+          Please review the relative path and file name." >&2'
+        - "   exit 2"
+        - fi
+        - if  [[ "{{Check}}" == True ]] ; then
+        - '   ansible-playbook -i "localhost," --check -c local -e "{{ExtraVariables}}"
+          "{{Verbose}}" "${PlaybookFile}"'
+        - else
+        - '   ansible-playbook -i "localhost," -c local -e "{{ExtraVariables}}" "{{Verbose}}"
+          "${PlaybookFile}"'
+        - fi
+#
