Fixing a bug where the correct role wasn't being assumed in the apply stage. Added the commands and a sanity check which will fail the job if the assume-role fails.

diff --git a/.github/workflows/awsnuke.yml b/.github/workflows/awsnuke.yml
--- a/.github/workflows/awsnuke.yml
+++ b/.github/workflows/awsnuke.yml
@@ -54,8 +54,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        # nuke_accts: ${{ fromJSON(needs.setup-prerequisites.outputs.matrix) }}
-        nuke_accts: [sprinkler-development]
+        nuke_accts: ${{ fromJSON(needs.setup-prerequisites.outputs.matrix) }}
     name: Sandbox Nuke
     permissions:
       id-token: write # This is required for requesting the JWT
@@ -107,15 +106,21 @@ jobs:
           $(echo "export AWS_ACCESS_KEY_ID=$(echo $(cat creds) | sed -n 's/.*"AccessKeyId": "\([^"]*\)".*/\1/p')")
           $(echo "export AWS_SECRET_ACCESS_KEY=$(echo $(cat creds) | sed -n 's/.*"SecretAccessKey": "\([^"]*\)".*/\1/p')")
           $(echo "export AWS_SESSION_TOKEN=$(echo $(cat creds) | sed -n 's/.*"SessionToken": "\([^"]*\)".*/\1/p')")
-          grep "MemberInfrastructureAccess" <<< $(aws sts get-caller-identity) || { echo 'Failed to assume role' ; exit $?; }
+          grep "MemberInfrastructureAccess" <<< $(aws sts get-caller-identity) || { echo 'Failed to assume role' ; exit 1; }
           $HOME/bin/aws-nuke --access-key-id "$AWS_ACCESS_KEY_ID" \
             --secret-access-key "$AWS_SECRET_ACCESS_KEY" \
             --session-token "$AWS_SESSION_TOKEN" \
             --config nuke-config.yml \
             --force
       - name: Nuke Apply (-no-dry-run)
-        # if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') }}
+        if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') }}
         run: |
+          # The environment gets reset between steps, so the role needs to be re-assumed.
+          aws sts assume-role --role-arn "arn:aws:iam::${ACCOUNT_NUMBER}:role/MemberInfrastructureAccess" --role-session-name githubactionsgotestrolesession > creds
+          $(echo "export AWS_ACCESS_KEY_ID=$(echo $(cat creds) | sed -n 's/.*"AccessKeyId": "\([^"]*\)".*/\1/p')")
+          $(echo "export AWS_SECRET_ACCESS_KEY=$(echo $(cat creds) | sed -n 's/.*"SecretAccessKey": "\([^"]*\)".*/\1/p')")
+          $(echo "export AWS_SESSION_TOKEN=$(echo $(cat creds) | sed -n 's/.*"SessionToken": "\([^"]*\)".*/\1/p')")
+          grep "MemberInfrastructureAccess" <<< $(aws sts get-caller-identity) || { echo 'Failed to assume role' ; exit 1; }
           $HOME/bin/aws-nuke --access-key-id "$AWS_ACCESS_KEY_ID" \
             --secret-access-key "$AWS_SECRET_ACCESS_KEY" \
             --session-token "$AWS_SESSION_TOKEN" \
@@ -181,7 +186,7 @@ jobs:
       - name: Nuke Apply (-no-dry-run)
         if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') }}
         run: |
-          # The action re-exports any variables declared via env: between steps, so the AWS credentials get overwritten and the role needs to be re-assumed.
+          # The environment gets reset between steps, so the AWS credentials get overwritten and the role needs to be re-assumed.
           aws sts assume-role --role-arn "arn:aws:iam::${ACCOUNT_NUMBER}:role/MemberInfrastructureAccess" --role-session-name githubactionsgotestrolesession > creds
           $(echo "export AWS_ACCESS_KEY_ID=$(echo $(cat creds) | sed -n 's/.*"AccessKeyId": "\([^"]*\)".*/\1/p')")
           $(echo "export AWS_SECRET_ACCESS_KEY=$(echo $(cat creds) | sed -n 's/.*"SecretAccessKey": "\([^"]*\)".*/\1/p')")
