test dry run on member accts

diff --git a/.github/workflows/awsnuke.yml b/.github/workflows/awsnuke.yml
--- a/.github/workflows/awsnuke.yml
+++ b/.github/workflows/awsnuke.yml
@@ -50,79 +50,79 @@ jobs:
           done <<< "$(jq -c -r '.[]' <<< $NUKE_BLOCKLIST_ACCOUNTS)" # Taking this approach as piping (|) to a read opens a subshell and passes the variables to it by value
           # Encoding and passing blocklist string as an output
           echo "account_blocklist_str=$(echo -n "${account_blocklist_str}" | base64 -w 0)" >> $GITHUB_OUTPUT
-  # nuke:
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       nuke_accts: ${{ fromJSON(needs.setup-prerequisites.outputs.matrix) }}
-  #   name: Sandbox Nuke
-  #   permissions:
-  #     id-token: write # This is required for requesting the JWT
-  #     contents: read # This is required for actions/checkout
-  #   needs: setup-prerequisites
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout Repository
-  #       uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
-  #     - name: Set Account Number
-  #       run: |
-  #         ACCOUNT_NUMBER=$(jq -r -e --arg account_name "${ACCOUNT_NAME}" '.account_ids[$account_name]' <<< $ENVIRONMENT_MANAGEMENT)
-  #         echo "::add-mask::$ACCOUNT_NUMBER"
-  #         echo "ACCOUNT_NUMBER=${ACCOUNT_NUMBER}" >> $GITHUB_ENV
-  #     - name: configure aws credentials
-  #       uses: aws-actions/configure-aws-credentials@4fc4975a852c8cd99761e2de1f4ba73402e44dd9 # v4.0.3
-  #       with:
-  #         role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
-  #         role-session-name: githubactionsrolesession
-  #         aws-region: ${{ env.AWS_REGION }}
-  #     - name: Setup Nuke Account String
-  #       run: |
-  #         accounts_str=''
-  #         accounts_str+="  \"${ACCOUNT_NUMBER}\": # ${ACCOUNT_NAME}"
-  #         accounts_str+=$'\n'
-  #         accounts_str+="    presets:"
-  #         accounts_str+=$'\n'
-  #         accounts_str+="      - \"common\""
-  #         accounts_str+=$'\n'
-  #         echo "$accounts_str"
-  #         echo "ACCOUNTS_STR<<EOF" >> $GITHUB_ENV
-  #         echo "$accounts_str" >> $GITHUB_ENV
-  #         echo "EOF" >> $GITHUB_ENV
-  #     - name: Setup Nuke Config
-  #       run: |
-  #         export accounts_str="$ACCOUNTS_STR"
-  #         export account_blocklist_str=$(echo "${{ needs.setup-prerequisites.outputs.account_blocklist_str }}" | base64 --decode)
-  #         cat scripts/nuke-config-template.txt | envsubst > nuke-config.yml
-  #     - name: Install AWS Nuke
-  #       run: |
-  #         echo "BEGIN: Install AWS Nuke"
-  #         mkdir -p $HOME/bin
-  #         wget -c "https://github.com/ekristen/aws-nuke/releases/download/${AWS_NUKE_VERSION}/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64.tar.gz" -O - | tar -xz -C $HOME/bin
-  #         chmod +x $HOME/bin/aws-nuke
-  #         echo "END: Install AWS Nuke"
-  #       env:
-  #         AWS_NUKE_VERSION: v3.51.1
-  #     - name: Nuke Plan (Dry Run)
-  #       run: |
-  #           aws sts assume-role \
-  #             --role-arn "arn:aws:iam::${ACCOUNT_NUMBER}:role/MemberInfrastructureAccess" \
-  #             --role-session-name githubactionsgotestrolesession > creds.json || {
-  #               echo "Failed to assume role"
-  #               exit 1
-  #           }
-  #           export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' creds.json)
-  #           export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' creds.json)
-  #           export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' creds.json)
+  nuke:
+    strategy:
+      fail-fast: false
+      matrix:
+        nuke_accts: ${{ fromJSON(needs.setup-prerequisites.outputs.matrix) }}
+    name: Sandbox Nuke
+    permissions:
+      id-token: write # This is required for requesting the JWT
+      contents: read # This is required for actions/checkout
+    needs: setup-prerequisites
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
+      - name: Set Account Number
+        run: |
+          ACCOUNT_NUMBER=$(jq -r -e --arg account_name "${ACCOUNT_NAME}" '.account_ids[$account_name]' <<< $ENVIRONMENT_MANAGEMENT)
+          echo "::add-mask::$ACCOUNT_NUMBER"
+          echo "ACCOUNT_NUMBER=${ACCOUNT_NUMBER}" >> $GITHUB_ENV
+      - name: configure aws credentials
+        uses: aws-actions/configure-aws-credentials@4fc4975a852c8cd99761e2de1f4ba73402e44dd9 # v4.0.3
+        with:
+          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
+          role-session-name: githubactionsrolesession
+          aws-region: ${{ env.AWS_REGION }}
+      - name: Setup Nuke Account String
+        run: |
+          accounts_str=''
+          accounts_str+="  \"${ACCOUNT_NUMBER}\": # ${ACCOUNT_NAME}"
+          accounts_str+=$'\n'
+          accounts_str+="    presets:"
+          accounts_str+=$'\n'
+          accounts_str+="      - \"common\""
+          accounts_str+=$'\n'
+          echo "$accounts_str"
+          echo "ACCOUNTS_STR<<EOF" >> $GITHUB_ENV
+          echo "$accounts_str" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+      - name: Setup Nuke Config
+        run: |
+          export accounts_str="$ACCOUNTS_STR"
+          export account_blocklist_str=$(echo "${{ needs.setup-prerequisites.outputs.account_blocklist_str }}" | base64 --decode)
+          cat scripts/nuke-config-template.txt | envsubst > nuke-config.yml
+      - name: Install AWS Nuke
+        run: |
+          echo "BEGIN: Install AWS Nuke"
+          mkdir -p $HOME/bin
+          wget -c "https://github.com/ekristen/aws-nuke/releases/download/${AWS_NUKE_VERSION}/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64.tar.gz" -O - | tar -xz -C $HOME/bin
+          chmod +x $HOME/bin/aws-nuke
+          echo "END: Install AWS Nuke"
+        env:
+          AWS_NUKE_VERSION: v3.51.1
+      - name: Nuke Plan (Dry Run)
+        run: |
+            aws sts assume-role \
+              --role-arn "arn:aws:iam::${ACCOUNT_NUMBER}:role/MemberInfrastructureAccess" \
+              --role-session-name githubactionsgotestrolesession > creds.json || {
+                echo "Failed to assume role"
+                exit 1
+            }
+            export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' creds.json)
+            export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' creds.json)
+            export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' creds.json)
         
-  #           echo "🔍 Verifying identity..."
-  #           aws sts get-caller-identity || {
-  #             echo "Invalid credentials"
-  #             exit 1
-  #           }
-  #           echo "Running AWS Nuke (dry run)..."
-  #           echo "${ACCOUNT_NAME}" | $HOME/bin/aws-nuke run \
-  #             --config nuke-config.yml \
-  #             --no-prompt
+            echo "🔍 Verifying identity..."
+            aws sts get-caller-identity || {
+              echo "Invalid credentials"
+              exit 1
+            }
+            echo "Running AWS Nuke (dry run)..."
+            echo "${ACCOUNT_NAME}" | $HOME/bin/aws-nuke run \
+              --config nuke-config.yml \
+              --no-prompt
 
   #     - name: Nuke Apply (Destructive)
   #       if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') }}
@@ -162,8 +162,8 @@ jobs:
   #       env:
   #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   #       if: ${{ failure() }}
-  #   env:
-  #     ACCOUNT_NAME: ${{ matrix.nuke_accts }}
+    env:
+      ACCOUNT_NAME: ${{ matrix.nuke_accts }}
 
   # testing-test account is not set up with OIDC because it is used to terratest OIDC-related resources. Therefore it's handled as a special case
   # using testing-ci user static credentials.
