Testing Nuke from matrix secret.

diff --git a/.github/workflows/awsnuke.yml b/.github/workflows/awsnuke.yml
--- a/.github/workflows/awsnuke.yml
+++ b/.github/workflows/awsnuke.yml
@@ -31,8 +31,10 @@ jobs:
       account_blocklist_str : ${{ steps.set-blocklist-string.outputs.account_blocklist_str }}
     steps:
       - id: set-matrix
+        name: Set Up Matrix
         run: echo "matrix=$(jq -c '.| map(select(. !="testing-test"))|sort' <<< $NUKE_ACCOUNTS)" >> $GITHUB_OUTPUT
       - id: set-blocklist-string
+        name: Set Up Blocklist
         run: |
           account_blocklist_str=''
           while read -r account_alias _; do
@@ -40,10 +42,8 @@ jobs:
           account_blocklist_str+="  - \"${account_number}\" # ${account_alias}"
           account_blocklist_str+=$'\n'
           done <<< "$(jq -c -r '.[]' <<< $NUKE_BLOCKLIST_ACCOUNTS)" # Taking this approach as piping (|) to a read opens a subshell and passes the variables to it by value
-          # Passing multi-line string output:
-          echo "account_blocklist_str<<EOF" >> $GITHUB_OUTPUT
-          echo "$account_blocklist_str" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
+          # Encoding and passing blocklist string as an output
+          echo "account_blocklist_str=$(echo -n "${account_blocklist_str}" | base64 -w 0)" >> $GITHUB_OUTPUT
   nuke:
     strategy:
       fail-fast: false
@@ -79,8 +79,8 @@ jobs:
           echo "EOF" >> $GITHUB_ENV
       - name: Setup Nuke Config
         run: |
-          export account_blocklist_str="${{ needs.setup-prerequisites.outputs.account_blocklist_str }}"
           export accounts_str="$ACCOUNTS_STR"
+          export account_blocklist_str=$(echo "${{ needs.setup-prerequisites.outputs.account_blocklist_str }}" | base64 --decode)
           cat scripts/nuke-config-template.txt | envsubst > nuke-config.yml
       - name: Install AWS Nuke
         run: |
@@ -92,13 +92,22 @@ jobs:
           echo "END: Install AWS Nuke"
         env:
           AWS_NUKE_VERSION: v2.19.0
-      - name: Nuke
+      - name: Nuke Plan (Dry Run)
         run: |
           aws sts assume-role --role-arn "arn:aws:iam::${ACCOUNT_NUMBER}:role/MemberInfrastructureAccess" --role-session-name githubactionsgotestrolesession > creds
           $(echo "export AWS_ACCESS_KEY_ID=$(echo $(cat creds) | sed -n 's/.*"AccessKeyId": "\([^"]*\)".*/\1/p')")
           $(echo "export AWS_SECRET_ACCESS_KEY=$(echo $(cat creds) | sed -n 's/.*"SecretAccessKey": "\([^"]*\)".*/\1/p')")
           $(echo "export AWS_SESSION_TOKEN=$(echo $(cat creds) | sed -n 's/.*"SessionToken": "\([^"]*\)".*/\1/p')")
-          aws sts get-caller-identity
+          grep "MemberInfrastructureAccess" <<< $(aws sts get-caller-identity) || { echo 'Failed to assume role' ; exit $?; }
+          $HOME/bin/aws-nuke --access-key-id "$AWS_ACCESS_KEY_ID" \
+            --secret-access-key "$AWS_SECRET_ACCESS_KEY" \
+            --session-token "$AWS_SESSION_TOKEN" \
+            --config nuke-config.yml \
+            --force
+            # --no-dry-run || exit_code=$?
+      - name: Nuke Apply (-no-dry-run)
+        if: ${{ github.event_name == 'schedule' }} || ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'}}
+        run: |
           $HOME/bin/aws-nuke --access-key-id "$AWS_ACCESS_KEY_ID" \
             --secret-access-key "$AWS_SECRET_ACCESS_KEY" \
             --session-token "$AWS_SESSION_TOKEN" \
@@ -123,3 +132,4 @@ jobs:
       #   run: echo "${{ needs.setup-prerequisites.outputs.account_blocklist_str }}"
     env:
       ACCOUNT_NAME: ${{ matrix.nuke_accts }}
+      account_blocklist: ${{ needs.setup-prerequisites.outputs.account_blocklist_str }}
