Test aws nuke using latest version

diff --git a/.github/workflows/awsnuke.yml b/.github/workflows/awsnuke.yml
--- a/.github/workflows/awsnuke.yml
+++ b/.github/workflows/awsnuke.yml
@@ -5,17 +5,17 @@ on:
     branches:
       - main
     paths:
-      - '.github/workflows/awsnuke.yml'
+      - ".github/workflows/awsnuke.yml"
   pull_request:
     branches:
       - main
     types: [opened, edited, reopened, synchronize]
     paths:
-      - '.github/workflows/awsnuke.yml'
+      - ".github/workflows/awsnuke.yml"
   schedule:
     # * is a special character in YAML so you have to quote this string
     # trigger every sunday at 12:00am
-    - cron: '0 12 * * 0'
+    - cron: "0 12 * * 0"
   workflow_dispatch:
 env:
   AWS_REGION: "eu-west-2"
@@ -34,7 +34,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
-      account_blocklist_str : ${{ steps.set-blocklist-string.outputs.account_blocklist_str }}
+      account_blocklist_str: ${{ steps.set-blocklist-string.outputs.account_blocklist_str }}
     steps:
       - id: set-matrix
         name: Set Up Matrix
@@ -51,6 +51,8 @@ jobs:
           # Encoding and passing blocklist string as an output
           echo "account_blocklist_str=$(echo -n "${account_blocklist_str}" | base64 -w 0)" >> $GITHUB_OUTPUT
   # nuke:
+  #   needs: setup-prerequisites
+  #   runs-on: ubuntu-latest
   #   strategy:
   #     fail-fast: false
   #     matrix:
@@ -59,8 +61,6 @@ jobs:
   #   permissions:
   #     id-token: write # This is required for requesting the JWT
   #     contents: read # This is required for actions/checkout
-  #   runs-on: ubuntu-latest
-  #   needs: setup-prerequisites
   #   steps:
   #     - name: Checkout Repository
   #       uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
@@ -96,25 +96,36 @@ jobs:
   #     - name: Install AWS Nuke
   #       run: |
   #         echo "BEGIN: Install AWS Nuke"
-  #         mkdir -p $HOME/bin 
+  #         mkdir -p $HOME/bin
   #         wget -c "https://github.com/ekristen/aws-nuke/releases/download/${AWS_NUKE_VERSION}/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64.tar.gz" -O - | tar -xz -C $HOME/bin
-  #         mv "$HOME/bin/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64" $HOME/bin/aws-nuke
   #         chmod +x $HOME/bin/aws-nuke
   #         echo "END: Install AWS Nuke"
   #       env:
   #         AWS_NUKE_VERSION: v3.51.1
   #     - name: Nuke Plan (Dry Run)
   #       run: |
-  #         aws sts assume-role --role-arn "arn:aws:iam::${ACCOUNT_NUMBER}:role/MemberInfrastructureAccess" --role-session-name githubactionsgotestrolesession > creds
-  #         $(echo "export AWS_ACCESS_KEY_ID=$(echo $(cat creds) | sed -n 's/.*"AccessKeyId": "\([^"]*\)".*/\1/p')")
-  #         $(echo "export AWS_SECRET_ACCESS_KEY=$(echo $(cat creds) | sed -n 's/.*"SecretAccessKey": "\([^"]*\)".*/\1/p')")
-  #         $(echo "export AWS_SESSION_TOKEN=$(echo $(cat creds) | sed -n 's/.*"SessionToken": "\([^"]*\)".*/\1/p')")
-  #         grep "MemberInfrastructureAccess" <<< $(aws sts get-caller-identity) || { echo 'Failed to assume role' ; exit 1; }
-  #         $HOME/bin/aws-nuke --access-key-id "$AWS_ACCESS_KEY_ID" \
-  #           --secret-access-key "$AWS_SECRET_ACCESS_KEY" \
-  #           --session-token "$AWS_SESSION_TOKEN" \
-  #           --config nuke-config.yml \
-  #           --force
+  #           aws sts assume-role \
+  #             --role-arn "arn:aws:iam::${ACCOUNT_NUMBER}:role/MemberInfrastructureAccess" \
+  #             --role-session-name githubactionsgotestrolesession > creds.json || {
+  #               echo "Failed to assume role"
+  #               exit 1
+  #           }
+        
+  #           export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' creds.json)
+  #           export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' creds.json)
+  #           export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' creds.json)
+        
+  #           echo "🔍 Verifying identity..."
+  #           aws sts get-caller-identity || {
+  #             echo "Invalid credentials"
+  #             exit 1
+  #           }
+        
+  #           echo "Running AWS Nuke (dry run)..."
+  #           echo "${ACCOUNT_NAME}" | $HOME/bin/aws-nuke run \
+  #             --config nuke-config.yml \
+  #             --force
+
   #     - name: Nuke Apply (-no-dry-run)
   #       if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') }}
   #       run: |
@@ -139,9 +150,8 @@ jobs:
   #       env:
   #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   #       if: ${{ failure() }}
-  #   env:
-  #     ACCOUNT_NAME: ${{ matrix.nuke_accts }}
-
+    env:
+      ACCOUNT_NAME: ${{ matrix.nuke_accts }}
 
   # testing-test account is not set up with OIDC because it is used to terratest OIDC-related resources. Therefore it's handled as a special case
   # using testing-ci user static credentials.
@@ -182,47 +192,70 @@ jobs:
           echo "BEGIN: Install AWS Nuke"
           mkdir -p $HOME/bin
           wget -c "https://github.com/ekristen/aws-nuke/releases/download/${AWS_NUKE_VERSION}/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64.tar.gz" -O - | tar -xz -C $HOME/bin
-          mv "$HOME/bin/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64" $HOME/bin/aws-nuke
           chmod +x $HOME/bin/aws-nuke
           echo "END: Install AWS Nuke"
         env:
           AWS_NUKE_VERSION: v3.51.1
       - name: Nuke Plan (Dry Run)
         run: |
-          aws sts assume-role --role-arn "arn:aws:iam::${ACCOUNT_NUMBER}:role/MemberInfrastructureAccess" --role-session-name githubactionsgotestrolesession > creds
-          $(echo "export AWS_ACCESS_KEY_ID=$(echo $(cat creds) | sed -n 's/.*"AccessKeyId": "\([^"]*\)".*/\1/p')")
-          $(echo "export AWS_SECRET_ACCESS_KEY=$(echo $(cat creds) | sed -n 's/.*"SecretAccessKey": "\([^"]*\)".*/\1/p')")
-          $(echo "export AWS_SESSION_TOKEN=$(echo $(cat creds) | sed -n 's/.*"SessionToken": "\([^"]*\)".*/\1/p')")
-          grep "MemberInfrastructureAccess" <<< $(aws sts get-caller-identity) || { echo 'Failed to assume role' ; exit 1; }
-          $HOME/bin/aws-nuke --access-key-id "$AWS_ACCESS_KEY_ID" \
-            --secret-access-key "$AWS_SECRET_ACCESS_KEY" \
-            --session-token "$AWS_SESSION_TOKEN" \
-            --config nuke-config.yml \
-            --force
-      - name: Nuke Apply (-no-dry-run)
-        if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') }}
-        run: |
-          # The environment gets reset between steps, so the AWS credentials get overwritten and the role needs to be re-assumed.
-          aws sts assume-role --role-arn "arn:aws:iam::${ACCOUNT_NUMBER}:role/MemberInfrastructureAccess" --role-session-name githubactionsgotestrolesession > creds
-          $(echo "export AWS_ACCESS_KEY_ID=$(echo $(cat creds) | sed -n 's/.*"AccessKeyId": "\([^"]*\)".*/\1/p')")
-          $(echo "export AWS_SECRET_ACCESS_KEY=$(echo $(cat creds) | sed -n 's/.*"SecretAccessKey": "\([^"]*\)".*/\1/p')")
-          $(echo "export AWS_SESSION_TOKEN=$(echo $(cat creds) | sed -n 's/.*"SessionToken": "\([^"]*\)".*/\1/p')")
-          grep "MemberInfrastructureAccess" <<< $(aws sts get-caller-identity) || { echo 'Failed to assume role' ; exit 1; }
-          $HOME/bin/aws-nuke --access-key-id "$AWS_ACCESS_KEY_ID" \
-            --secret-access-key "$AWS_SECRET_ACCESS_KEY" \
-            --session-token "$AWS_SESSION_TOKEN" \
-            --config nuke-config.yml \
-            --force \
-            --no-dry-run
-      - name: Slack failure notification
-        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
-        with:
-          webhook-type: incoming-webhook
-          payload: |
-            {"blocks":[{"type": "section","text": {"type": "mrkdwn","text": ":no_entry: Failed GitHub Action:"}},{"type": "section","fields":[{"type": "mrkdwn","text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"},{"type": "mrkdwn","text": "*Job:*\n${{ github.job }}"},{"type": "mrkdwn","text": "*Repo:*\n${{ github.repository }}"}]}]}
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-        if: ${{ failure() }}
+            aws sts assume-role \
+              --role-arn "arn:aws:iam::${ACCOUNT_NUMBER}:role/MemberInfrastructureAccess" \
+              --role-session-name githubactionsgotestrolesession > creds.json || {
+                echo "Failed to assume role"
+                exit 1
+            }
+        
+            export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' creds.json)
+            export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' creds.json)
+            export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' creds.json)
+        
+            echo "🔍 Verifying identity..."
+            aws sts get-caller-identity || {
+              echo "Invalid credentials"
+              exit 1
+            }
+        
+            echo "Running AWS Nuke (dry run)..."
+            echo "${ACCOUNT_NAME}" | $HOME/bin/aws-nuke run \
+              --config nuke-config.yml \
+              --force
+
+        
+      # - name: Nuke Apply (Destructive)
+      #   # if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') }}
+      #   run: |
+      #       aws sts assume-role \
+      #         --role-arn "arn:aws:iam::${ACCOUNT_NUMBER}:role/MemberInfrastructureAccess" \
+      #         --role-session-name githubactionsgoliveapply > creds.json || {
+      #           echo "Failed to assume role"
+      #           exit 1
+      #       }
+
+      #       export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' creds.json)
+      #       export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' creds.json)
+      #       export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' creds.json)
+        
+      #       echo "🔍 Verifying identity..."
+      #       aws sts get-caller-identity || {
+      #         echo "Invalid credentials"
+      #         exit 1
+      #       }
+        
+      #       echo "☠️ Running AWS Nuke (full apply)..."
+      #       $HOME/bin/aws-nuke run \
+      #         --config nuke-config.yml \
+      #         --force \
+      #         --no-dry-run
+
+      #   - name: Slack failure notification
+    #     uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
+    #     with:
+    #       webhook-type: incoming-webhook
+    #       payload: |
+    #         {"blocks":[{"type": "section","text": {"type": "mrkdwn","text": ":no_entry: Failed GitHub Action:"}},{"type": "section","fields":[{"type": "mrkdwn","text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"},{"type": "mrkdwn","text": "*Job:*\n${{ github.job }}"},{"type": "mrkdwn","text": "*Repo:*\n${{ github.repository }}"}]}]}
+    #     env:
+    #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+    #     if: ${{ failure() }}
     env:
       AWS_ACCESS_KEY_ID:  ${{ secrets.TESTING_AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY:  ${{ secrets.TESTING_AWS_SECRET_ACCESS_KEY }}
