test

diff --git a/.github/workflows/plan.yml b/.github/workflows/plan.yml
--- a/.github/workflows/plan.yml
+++ b/.github/workflows/plan.yml
@@ -26,6 +26,9 @@ on:
 # ACCOUNT_NAME: "${{ input.application }}-${{ input.environment }}"
 # APPLICATION: "${{ input.application }}"
 
+env:
+  ENVIRONMENT_MANAGEMENT: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}
+
 jobs:
 
   plan:
@@ -35,8 +38,15 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
 
-#      - name: Set Account Number
-#        run: echo "ACCOUNT_NUMBER=$(jq -r -e --arg account_name "${ACCOUNT_NAME}" '.account_ids[$account_name]' <<< ${{ secrets.modernisation_platform_environments }})" >> $GITHUB_ENV
+      - name: Get Account Number
+        run: |
+          echo "account name: ${ACCOUNT_NAME}"
+          ACCOUNT_NUMBER=$(jq -r -e --arg account_name "${ACCOUNT_NAME}" '.account_ids[$account_name]' <<< $ENVIRONMENT_MANAGEMENT)
+          if [[ -z $ACCOUNT_NUMBER ]]; then
+            echo "Could not retrieve account number from MODERNISATION_PLATFORM_ENVIRONMENTS github secret"
+            exit 1
+          fi
+          echo "ACCOUNT_NUMBER=${ACCOUNT_NUMBER}" >> $GITHUB_ENV
 
 #     - name: configure aws credentials
 #       uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838  # v1.7.0
