test

diff --git a/.github/workflows/reusable_terraform_plan_apply.yml b/.github/workflows/reusable_terraform_plan_apply.yml
--- a/.github/workflows/reusable_terraform_plan_apply.yml
+++ b/.github/workflows/reusable_terraform_plan_apply.yml
@@ -17,12 +17,17 @@ on:
         required: false
         description: "Set to plan, plan_apply or apply"
         default: plan
-      additional_tfargs:
+      init_plan_apply_tfargs:
+        type: string
+        required: false
+        description: "Any terraform arguments to be passed into terrafrom init, plan and apply, e.g. --lock-timeout=300s"
+        default: "-input=false -lock-timeout=300s"
+      plan_apply_tfargs:
         type: string
         required: false
         description: "Any additional terraform arguments to be passed in to terraform plan/apply, e.g. -var 'foo=bar'"
         default: ""
-      do_state_refresh:
+      do_state_refresh_on_plan:
         type: boolean
         required: false
         description: "Set to true to do a state refresh prior to the plan"
@@ -48,16 +53,123 @@ jobs:
 
   plan:
     name: "1. plan"  # at time or writing, jobs are sorted alphabetically in the UI for reusable jobs
-    if: inputs.action == 'plan' || inputs.action == 'plan_apply'      
+    if: inputs.action == 'plan' || inputs.action == 'plan_apply'
     runs-on: ubuntu-latest
     outputs:
       plan_exitcode: "${{ steps.plan.outputs.exitcode }}"
     steps:
       - name: Debug
         run: |
-          echo "application=${{ inputs.application }} environment=${{ inputs.environment }} action=${{ inputs.action }}"
-          echo "additional_tfargs=${{ inputs.additional_tfargs }} do_state_refresh=${{ inputs.do_state_refresh }} post_plan_to_pr=${{ inputs.post_plan_to_pr }}"
+          echo "application=${{ inputs.application }}"
+          echo "environment=${{ inputs.environment }}"
+          echo "action=${{ inputs.action }}"
+          echo "init_plan_apply_tfargs=${{ inputs.init_plan_apply_tfargs }}"
+          echo "plan_apply_tfargs=${{ inputs.plan_apply_tfargs }}"
+          echo "do_state_refresh_on_plan=${{ inputs.do_state_refresh_on_plan }}"
+          echo "post_plan_to_pr=${{ inputs.post_plan_to_pr }}"
 
+      - name: Checkout Repository
+        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
+
+      - name: Get AWS Account Number
+        run: |
+          ACCOUNT_NUMBER=$(jq -r -e --arg account_name "${ACCOUNT_NAME}" '.account_ids[$account_name]' <<< $ENVIRONMENT_MANAGEMENT)
+          echo "ACCOUNT_NUMBER=${ACCOUNT_NUMBER}" >> $GITHUB_ENV
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838  # v1.7.0
+        with:
+          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
+          role-session-name: githubactionsrolesession
+          aws-region: "eu-west-2"
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1  # v2.0.3
+        with:
+          terraform_version: "~1"
+          terraform_wrapper: false
+
+      # separate everything into separate steps so easier to find stuff in UI
+      - name: Terraform Init
+        working-directory: "terraform/environments/${{ inputs.application }}"
+        run: |
+          terraform --version
+          echo "terraform init ${{ inputs.init_plan_apply_tfargs }}"
+          terraform init ${{ inputs.init_plan_apply_tfargs }}
+
+      - name: Terraform Workspace Select
+        working-directory: "terraform/environments/${{ inputs.application }}"
+        run: |
+          terraform workspace select "${WORKSPACE_NAME}"
+
+      # optional state refresh, can be useful if AWS often changes stuff behind the scenes
+      - name: Terraform State Refresh (Optional)
+        if: inputs.do_state_refresh_on_plan == true
+        working-directory: "terraform/environments/${{ inputs.application }}"
+        run: |
+          set -o pipefail
+          tf_args="${{ inputs.init_plan_apply_tfargs }} ${{ inputs.additional_tfargs }}"
+          echo "terraform apply -refresh-only -auto-approve ${tf_args}"
+          terraform apply -refresh-only -auto-approve ${tf_args} | bash ${GITHUB_WORKSPACE}/scripts/redact-output.sh
+
+      - name: Terraform Plan
+        id: plan
+        env:
+          POST_PLAN_TO_PR: "${{ github.event_name == 'pull_request' && steps.plan.outputs.exitcode == '2' && inputs.post_plan_to_pr == true }}"
+        working-directory: "terraform/environments/${{ inputs.application }}"
+        run: |
+          set -o pipefail
+          exitcode=0
+          tf_args="-detailed-exitcode ${{ inputs.init_plan_apply_tfargs }} ${{ inputs.additional_tfargs }}"
+          [[ ${POST_PLAN_TO_PR} == 'true' ]] && tf_args="${tf_args} -no-color"
+          [[ ${{ inputs.do_state_refresh_on_plan }} == 'true' ]] && tf_args="${tf_args} -refresh=false"
+          echo "terraform plan ${tf_args}"
+          terraform plan ${tf_args} | bash ${GITHUB_WORKSPACE}/scripts/redact-output.sh | tee tfplan.txt || exitcode=$?
+          echo "exitcode=${exitcode}"  # 0=clean plan, 1=error, 2=stuff in plan
+          echo "exitcode=${exitcode}" >> $GITHUB_OUTPUT
+          (( exitcode == 1 )) && exit 1 || exit 0
+
+      - name: Create Plan PR message (Optional)
+        if: github.event_name == 'pull_request' && steps.plan.outputs.exitcode == '2' && inputs.post_plan_to_pr == true
+        working-directory: "terraform/environments/${{ inputs.application }}"
+        run: |
+          comment() {
+            url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+            len=$(cat tfplan.txt | wc -c)
+            echo '**`${{ env.WORKSPACE_NAME }}`** terragrunt plan on `${{ github.event_name }}` event [#${{ github.run_number }}]'(${url})
+            echo
+            echo '```'
+            head -c 65476 tfplan.txt
+            echo
+            echo '```'
+            if [[ $len -gt 65476 ]]; then
+              echo "** Truncated output.  See $url for the rest **"
+            fi
+          }
+          echo 'TF_PLAN_OUT<<EOF' >> $GITHUB_ENV
+          comment >> $GITHUB_ENV
+          echo 'EOF' >> $GITHUB_ENV
+
+      - name: Post Plan to PR (Optional)
+        if: github.event_name == 'pull_request' && steps.plan.outputs.exitcode == '2' && inputs.post_plan_to_pr == true
+        env:
+          message: "${{ env.TF_PLAN_OUT }}"
+        run: |
+          escaped_message=$(echo "$message" | jq -Rsa .)
+          curl -sS -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
+            -d '{"body":'"${escaped_message}"'}'
+
+
+  apply:
+    name: "2. apply"  # at time or writing, jobs are sorted alphabetically in the UI for reusable jobs
+    needs: plan
+    if: (inputs.action == 'plan_apply' || inputs.action == 'apply') && needs.plan.outputs.plan_exitcode == '2'
+    runs-on: ubuntu-latest
+    environment: "${{ inputs.application }}-${{ inputs.environment }}"
+    steps:
       - name: Checkout Repository
         uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
 
@@ -83,78 +195,28 @@ jobs:
         working-directory: "terraform/environments/${{ inputs.application }}"
         run: |
           terraform --version
-          terraform init -input=false -lock-timeout=300s
+          echo "terraform init ${{ inputs.init_plan_apply_tfargs }}"
+          terraform init ${{ inputs.init_plan_apply_tfargs }}
 
       - name: Terraform Workspace Select
         working-directory: "terraform/environments/${{ inputs.application }}"
         run: |
           terraform workspace select "${WORKSPACE_NAME}"
 
-      - name: Terraform State Refresh
-        if: inputs.do_state_refresh == true
-        working-directory: "terraform/environments/${{ inputs.application }}"
-        run: |
-          terraform apply -refresh-only -auto-approve {{ inputs.additional_tfargs }} | bash ${GITHUB_WORKSPACE}/scripts/redact-output.sh
-
       - name: Terraform Plan
         id: plan
-        env:
-          POST_PLAN_TO_PR: "${{ github.event_name == 'pull_request' && steps.plan.outputs.exitcode == '2' && inputs.post_plan_to_pr == true }}"
         working-directory: "terraform/environments/${{ inputs.application }}"
         run: |
           set -o pipefail
-          exitcode=0
-          tf_args="-detailed-exitcode ${{ inputs.additional_tfargs }}"
-          [[ ${POST_PLAN_TO_PR} == 'true' ]] && tf_args="${tg_args} -no-color"
+          tf_args="-out x.tfplan ${{ inputs.init_plan_apply_tfargs }} ${{ inputs.additional_tfargs }}"
           echo "terraform plan ${tf_args}"
-          terraform plan ${tf_args} | bash ${GITHUB_WORKSPACE}/scripts/redact-output.sh | tee tfplan.txt || exitcode=$?
-          echo "exitcode=${exitcode}"
-          echo "exitcode=${exitcode}" >> $GITHUB_OUTPUT
-          (( exitcode == 1 )) && exit 1 || exit 0
+          terraform plan ${tf_args} | bash ${GITHUB_WORKSPACE}/scripts/redact-output.sh
 
-      - name: Create Plan PR message
-        if: github.event_name == 'pull_request' && steps.plan.outputs.exitcode == '2' && inputs.post_plan_to_pr == true
+      - name: Terraform Apply
+        id: plan
         working-directory: "terraform/environments/${{ inputs.application }}"
         run: |
-          comment() {
-            url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-            len=$(cat tfplan.txt | wc -c)
-            echo '**`${{ env.WORKSPACE_NAME }}`** terragrunt plan on `${{ github.event_name }}` event [#${{ github.run_number }}]'(${url})
-            echo
-            echo '```'
-            head -c 65476 tfplan.txt
-            echo
-            echo '```'
-            if [[ $len -gt 65476 ]]; then
-              echo "** Truncated output.  See $url for the rest **"
-            fi
-          }
-          echo 'TF_PLAN_OUT<<EOF' >> $GITHUB_ENV
-          comment >> $GITHUB_ENV
-          echo 'EOF' >> $GITHUB_ENV
-
-      - name: Post Plan to PR
-        if: github.event_name == 'pull_request' && steps.plan.outputs.exitcode == '2' && inputs.post_plan_to_pr == true
-        env:
-          message: "${{ env.TF_PLAN_OUT }}"
-        run: |
-          escaped_message=$(echo "$message" | jq -Rsa .)
-          curl -sS -X POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
-            -d '{"body":'"${escaped_message}"'}'
-
-
-  apply:
-    name: "2. apply"  # at time or writing, jobs are sorted alphabetically in the UI for reusable jobs
-    needs: plan
-    #if: (inputs.action == 'plan_apply' || inputs.action == 'apply') && needs.plan.outputs.plan_exitcode == '2' 
-    if: (inputs.action == 'plan_apply' || inputs.action == 'apply') 
-    runs-on: ubuntu-latest
-    environment: "${{ inputs.application }}-${{ inputs.environment }}"
-    steps:
-      - name: Debug
-        run: |
-          echo "${{ needs.plan.outputs.plan_exitcode }}"          
-      
+          set -o pipefail
+          tf_args="x.tfplan ${{ inputs.init_plan_apply_tfargs }} ${{ inputs.additional_tfargs }}"
+          echo "terraform apply ${tf_args}"
+          # terraform apply ${tf_args} | bash ${GITHUB_WORKSPACE}/scripts/redact-output.sh
